################################################################################
#
# sdl2_mixer
#
################################################################################

SDL2_MIXER_VERSION = 2.6.1
SDL2_MIXER_SOURCE = SDL2_mixer-$(SDL2_MIXER_VERSION).tar.gz
SDL2_MIXER_SITE =  https://github.com/libsdl-org/SDL_mixer/releases/download/release-$(SDL2_MIXER_VERSION)
SDL2_MIXER_LICENSE = Zlib
SDL2_MIXER_LICENSE_FILES = COPYING.txt
SDL2_MIXER_INSTALL_STAGING = YES
SDL2_MIXER_DEPENDENCIES = sdl2 host-pkgconf

SDL2_MIXER_SUPPORTS_IN_SOURCE_BUILD = NO

ifeq ($(BR2_PACKAGE_LIBXMP),y)
SDL_MIXER_CONF_OPTS += -DSDL2MIXER_MOD_XMP=ON -DSDL2MIXER_MOD_XMP_SHARED=ON
SDL2_MIXER_DEPENDENCIES += libxmp
else
SDL_MIXER_CONF_OPTS += -DSDL2MIXER_MOD_XMP=OFF
endif

ifeq ($(BR2_PACKAGE_FLUIDSYNTH)$(BR2_PACKAGE_TIMIDITY),)
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_MIDI=OFF
endif

ifeq ($(BR2_PACKAGE_FLUIDSYNTH),y)
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_MIDI_FLUIDSYNTH=ON -DSDL2MIXER_MIDI_FLUIDSYNTH_SHARED=ON
SDL2_MIXER_DEPENDENCIES += fluidsynth
else
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_MIDI_FLUIDSYNTH=OFF
endif

ifeq ($(BR2_PACKAGE_TIMIDITY),y)
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_MIDI_TIMIDITY=ON
SDL2_MIXER_DEPENDENCIES += timidity
else
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_MIDI_TIMIDITY=OFF
endif

ifeq ($(BR_PACKAGE_LIBOGG)$(BR2_PACKAGE_OPUS)$(BR2_PACKAGE_OPUSFILE),yyy)
SDL2_MIXER_CONF_OPTS += -DSDL2MIXER_OPUS_SHARED=ON
SDL2_MIXER_DEPENDENCIES += libogg opus libopusfile
endif

#ifeq ($(BR2_PACKAGE_SDL2_MIXER_USE_LIBFLAC),y)
#SDL2_MIXER_CONF_OPTS += --enable-music-flac
#SDL2_MIXER_DEPENDENCIES += flac
#else
#SDL2_MIXER_CONF_OPTS += --disable-music-flac
#endif

#ifeq ($(BR2_PACKAGE_SDL2_MIXER_USE_LIBMODPLUG),y)
#SDL2_MIXER_CONF_OPTS += --enable-music-mod-modplug
#SDL2_MIXER_DEPENDENCIES += libmodplug
#else
#SDL2_MIXER_CONF_OPTS += --disable-music-mod-modplug
#endif

#ifeq ($(BR2_PACKAGE_TREMOR),y)
#SDL2_MIXER_CONF_OPTS += --enable-music-ogg-tremor
#SDL2_MIXER_DEPENDENCIES += tremor
#else
#SDL2_MIXER_CONF_OPTS += --disable-music-ogg-tremor
#endif

$(eval $(cmake-package))
